# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
title:              Open Minaret
logo:               # Logo image URL
description:         َللهُمَّ اِنِّىْ اَسْأَلُكَ عِلْمًا نَافِعًا وَعَمَلاً مُتَقَبَّلاً وَرِزْقًا وَاسِعًا وَاِلَى الْخَيْرِ قَرِّبْنَا وَعَنِ الشَّرِّ بَعِّدْنَا
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'http://minaret.cubicless.com' # The base hostname & protocol for your site
twitter:            https://twitter.com/cubiclessmedia
facebook:           https://www.facebook.com/cubiclessmedia
instagram:          https://www.instagram.com/cubiclessmedia

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:     Faruq Sandi
    bio:      Computer science nerd.
    gravatar: https://s.gravatar.com/avatar/4c024d0d93d6048d89cb8d8b7db66af9?s=150
    email:    sandi@cubicless.com
    website:  http://cubicless.com
    github:   https://github.com/faruqsandi
    twitter:  https://twitter.com/faruqsandi